{% set name = "openff-nagl" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-nagl/archive/v{{ version }}.tar.gz
  sha256: f8b919a43de48f08e810a76513609a3bd0d994c70a39c5f3fde37a4af20252e0

build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"

requirements:
  host:
    - python >=3.9
    - pip
    - versioneer-518
  run:
    - python >=3.9
    - click
    - click-option-group
    - tqdm
    - openff-toolkit-base >=0.11.0
    - openff-units
    - pydantic
    - sqlalchemy
    - sqlite
    - pytorch
    - pytorch-lightning
    - rich


test:
  imports:
    - openff.nagl

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A library for applying graph convolutional neural networks to molecules
  dev_url: https://github.com/openforcefield/openff-nagl

extra:
  recipe-maintainers:
    - lilyminium
