{% set name = "openff-nagl" %}
{% set version = "0.4.0" %}

package:
  name: openff-toolkit-split
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-nagl/archive/v{{ version }}.tar.gz
  sha256: 4dcfbef28ff21d8bf033209d014fc1292ea153a5149d1c88b74ecad7a3881a3a

build:
  number: 0

outputs:
  - name: openff-nagl-base
    script: build_base.sh
    build:
      noarch: python
    requirements:
      host:
        - python >=3.10
        - pip
        - versioneer-518
      run:
        - python >=3.10
        - click
        - click-option-group
        - importlib_resources
        - tqdm
        - openff-toolkit-base >=0.11.0
        - openff-units
        - pyyaml
        - pydantic <3
        - pytorch >=2.0
        - pytorch-lightning
        - rdkit
        - rich
    test:
      imports:
        - openff.nagl

  - name: openff-nagl
    build:
      noarch: python
    requirements:
      host:
        - python >=3.10
      run:
        - python >=3.10
        - openff-nagl-models >=0.1.0
        - pyarrow
        - dgl >=1.0,<=2.1
        - dask-jobqueue
        - openff-recharge
        - {{ pin_subpackage('openff-nagl-base', exact=True) }}
    test:
      imports:
        - openff.nagl
      files:
        - test_models_loadable.py
      commands:
        - python test_models_loadable.py

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A library for applying graph convolutional neural networks to molecules
  dev_url: https://github.com/openforcefield/openff-nagl

extra:
  recipe-maintainers:
    - mattwthompson
    - j-wags
    - lilyminium
