{% set name = "openff-nagl" %}
{% set version = "0.3.4" %}

package:
  name: openff-toolkit-split
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-nagl/archive/v{{ version }}.tar.gz
  sha256: e3db29b0ba2812933d5b90438c7f25b9117622a005dfacf85cd591cff21ac9f0

build:
  number: 0

outputs:
  - name: openff-nagl-base
    script: build_base.sh
    build:
      noarch: python
    requirements:
      host:
        - python >=3.9
        - pip
        - versioneer-518
      run:
        - python >=3.9
        - click
        - click-option-group
        - tqdm
        - openff-toolkit-base >=0.11.0
        - openff-units
        - pyarrow
        - pydantic <3
        - pytorch
        - pytorch-lightning
        - rdkit
        - rich
    test:
      imports:
        - openff.nagl

  - name: openff-nagl
    build:
      noarch: python
    requirements:
      host:
        - python >=3.9
      run:
        - python >=3.9
        - openff-nagl-models >=0.1.0
        - dgl >=1.0
        - dask-jobqueue
        - {{ pin_subpackage('openff-nagl-base', exact=True) }}
    test:
      imports:
        - openff.nagl
      files:
        - test_models_loadable.py
      commands:
        - python test_models_loadable.py

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A library for applying graph convolutional neural networks to molecules
  dev_url: https://github.com/openforcefield/openff-nagl

extra:
  recipe-maintainers:
    - mattwthompson
    - j-wags
    - lilyminium
