{% set name = "openff-nagl" %}
{% set version = "0.3.0" %}

package:
  name: openff-toolkit-split
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-nagl/archive/v{{ version }}.tar.gz
  sha256: 71efbe79bb6d113b831a82cb81fd4ce0b05096e11cee4ad6def9dcc468142921

build:
  number: 0
  

outputs:
  - name: openff-nagl-base
    script: "{{ PYTHON }} -m pip install . -vv --no-deps"
    build:
      noarch: python
    requirements:
      host:
        - python >=3.9
        - pip
        - versioneer-518
      run:
        - python >=3.9
        - click
        - click-option-group
        - tqdm
        - openff-toolkit-base >=0.11.0
        - openff-units
        - pyarrow
        - pydantic <3
        - pytorch
        - pytorch-lightning
        - rdkit
        - rich
    test:
      imports:
        - openff.nagl

  - name: openff-nagl
    build:
      noarch: python
    requirements:
      host:
        - python >=3.9
      run:
        - python >=3.9
        - dgl >=1.0
        - dask-jobqueue
        - {{ pin_subpackage('openff-nagl-base', exact=True) }}
    test:
      imports:
        - openff.nagl

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A library for applying graph convolutional neural networks to molecules
  dev_url: https://github.com/openforcefield/openff-nagl

extra:
  recipe-maintainers:
    - lilyminium
